export const envObject = {
  BASE_URL: import.meta.env.VITE_REACT_APP_BASE_URL,
  API_URL: import.meta.env.VITE_REACT_APP_API_URL,

  CLICKUP_CLIENT_ID: import.meta.env.VITE_REACT_APP_CLICKUP_CLIENT_ID,
  CLICKUP_REDIRECT_URI: import.meta.env.VITE_REACT_APP_CLICKUP_REDIRECT_URI,

  JIRA_CLIENT_ID: import.meta.env.VITE_REACT_APP_JIRA_CLIENT_ID,
  JIRA_REDIRECT_URI: import.meta.env.VITE_REACT_APP_JIRA_REDIRECT_URI,

  FIREBASE_APIKEY: import.meta.env.VITE_REACT_APP_FIREBASE_APIKEY,
  FIREBASE_AUTHDOMAIN: import.meta.env.VITE_REACT_APP_FIREBASE_AUTHDOMAIN,
  FIREBASE_PROJECTID: import.meta.env.VITE_REACT_APP_FIREBASE_PROJECTID,
  FIREBASE_STORAGEBUCKET: import.meta.env.VITE_REACT_APP_FIREBASE_STORAGEBUCKET,
  FIREBASE_MESSAGINGSENDERID: import.meta.env.VITE_REACT_APP_FIREBASE_MESSAGINGSENDERID,
  FIREBASE_APPID: import.meta.env.VITE_REACT_APP_FIREBASE_APPID,
  FIREBASE_MEASUREMENTID: import.meta.env.VITE_REACT_APP_FIREBASE_MEASUREMENTID,
  FIREBASE_VAPIDKEY: import.meta.env.VITE_REACT_APP_FIREBASE_VAPIDKEY,

  GOOGLE_CLIENT_ID: import.meta.env.VITE_REACT_APP_GOOGLE_CLIENT_ID,
  GOOGLE_REDIRECT_URI: import.meta.env.VITE_REACT_APP_GOOGLE_REDIRECT_URI,
  GOOGLE_REDIRECT_SETTING_URI: import.meta.env.VITE_REACT_APP_GOOGLE_DRIVE_USER_REDIRECT_URI,

  ONE_REDIRECT_URI: import.meta.env.VITE_REACT_APP_ONE_REDIRECT_URI,
  ONE_CLIENT_ID: import.meta.env.VITE_REACT_APP_ONE_CLIENT_ID,
  GOOGLE_LOGIN_CLIENT_ID: import.meta.env.VITE_REACT_APP_GOOGLE_LOGIN_CLIENT_ID,

  EXTENSION_ID: import.meta.env.VITE_REACT_APP_EXTENSION_ID,
};
